//EL GLOBAL THIS ES SIMILAR AL OBJETO GLOBAL 
//QUIERE DECIR QUE SI VEMOS EN EL NAVEGADOR UN OBJETO WINDOW, SELF O THIS VAMOS A OBTENER UN
//RESULTADO

//EL GLOBAL THIS, PROPORCIONA UNA FROMA ESTANDAR PARA ACCEDER AL VALOR GLOBAL, OSEA SE PUEDE
//ACCEDER AL OBJETO GLOBAL NO SOLO DESDE EL NAVEGADOR SI NO DESDE LAS APLICACIONES CON NODE

console.log(window);
console.log(globalThis);
